[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Flash over SWD with probe-rs (user choice).
runner = "probe-rs run --chip RP235x"
# Alternative: picotool load -u -v -x -t elf

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
